## Task-1

## Grip@ Spark Foundation

#### Supervised Machine Learning

### Linear Regression

#### In this regression task we will going to predict the score of the students based on the number of hours they studied,it is a simple linear regression problem as it consist only two variables.

### Author:Pragya Patidar

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
data=pd.read_excel('spark 1.xlsx')

In [3]:
data.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [4]:
x=data["Hours"]

In [5]:
x.head()

0    2.5
1    5.1
2    3.2
3    8.5
4    3.5
Name: Hours, dtype: float64

In [10]:
x=np.array([data["Hours"]]).reshape(-1,1)
x

array([[2.5],
       [5.1],
       [3.2],
       [8.5],
       [3.5],
       [1.5],
       [9.2],
       [5.5],
       [8.3],
       [2.7],
       [7.7],
       [5.9],
       [4.5],
       [3.3],
       [1.1],
       [8.9],
       [2.5],
       [1.9],
       [6.1],
       [7.4],
       [2.7],
       [4.8],
       [3.8],
       [6.9],
       [7.8]])

In [11]:
y=data["Scores"]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [14]:
model=LinearRegression()

In [15]:
model.fit(x_train,y_train)

LinearRegression()

In [16]:
score1=model.score(x_train,y_train)

In [17]:
score1

0.9681980033905908

In [18]:
score2=model.score(x_test,y_test)

In [19]:
score2

0.8933827573294114

In [23]:
predict=model.predict(x_test)

In [24]:
predict

array([ 9.93952968, 32.84320126, 18.26813752, 86.97915227, 48.45934097,
       78.65054442, 61.99332873, 75.52731648])

In [32]:
x1=np.array([9.25]).reshape(-1,1)

In [33]:
x1

array([[9.25]])

In [34]:
predict1=model.predict(x1)


In [35]:
predict1

array([94.78722213])